/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Fullscene_0807_ver.gltf --transform 
Files: Fullscene_0807_ver.gltf [614.95KB] > D:\PDS_WorkSpace\pds_component_3d\public\Upload\Model\Fullscene_0807_ver_exports\export_with_full_collections\Fullscene_0807_ver-transformed.glb [3.22MB] (-423%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Fullscene_0807_ver-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[5.486, 1.846, 25.725]} scale={0.001}>
        <mesh geometry={nodes.Mesh262.geometry} material={materials['07 - Default.001']} />
        <mesh geometry={nodes.Mesh262_1.geometry} material={materials.PaletteMaterial001} />
      </group>
      <mesh geometry={nodes['ENV_CTRL-ROOM_pillars'].geometry} material={materials.PaletteMaterial002} position={[11.729, 1.145, 28.265]} scale={0.001} />
      <mesh geometry={nodes.ENV_WALL_Cube.geometry} material={nodes.ENV_WALL_Cube.material} position={[-4.086, 1.135, -4.319]} rotation={[0, Math.PI / 2, 0]} scale={[0.072, 1.15, 15.544]} />
      <mesh geometry={nodes.ENV_GROUND_Ground.geometry} material={materials['Ground_Mat.001']} position={[-0.842, -0.103, 3]} scale={[17.839, 17.839, 28.772]} />
      <mesh geometry={nodes.ENV_STAIRS_Switchgear_Stair001.geometry} material={materials.PaletteMaterial003} position={[5.383, 1.088, 10.262]} scale={0.001} />
      <group position={[-3.135, 0.787, 28.289]} rotation={[0, -Math.PI / 2, 0]} scale={0.001}>
        <mesh geometry={nodes.Mesh1982.geometry} material={materials.PaletteMaterial004} />
        <mesh geometry={nodes.Mesh1982_1.geometry} material={materials.PaletteMaterial005} />
        <mesh geometry={nodes.Mesh1982_2.geometry} material={materials.PaletteMaterial006} />
      </group>
      <mesh geometry={nodes['110kV-GIS_112_CB_PDS-S500-AE'].geometry} material={materials.lambert19} position={[-3.141, 2.58, 8.891]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.018, 0.038, 0.038]} />
      <mesh geometry={nodes['110kV-GIS_112_DS@1_DS'].geometry} material={materials['Material.072']} position={[-4.038, 1.532, 9.313]} rotation={[0, 0, 1.571]} scale={0.266} />
      <mesh geometry={nodes['110kV-GIS_112_DS@2_DS'].geometry} material={materials['Material.077']} position={[-4.822, 2.528, 9.128]} scale={1.142} />
      <mesh geometry={nodes['110kV-GIS_112_CT_CT'].geometry} material={materials['Material.065']} position={[-3.717, 2.526, 9.313]} scale={[0.402, 1.119, 0.402]} />
      <mesh geometry={nodes['110kV-GIS_112_CT_PDS-US02F'].geometry} material={materials['PDS_US02C_180124_3_2_blinn1.001']} position={[-4.829, 2.859, 9.313]} rotation={[-0.917, -Math.PI / 2, 0]} scale={1.112} />
      <group position={[-2.476, 1.188, 9.313]} scale={[0.299, 0.898, 0.447]}>
        <mesh geometry={nodes.Cube042.geometry} material={materials.PaletteMaterial007} />
        <mesh geometry={nodes.Cube042_1.geometry} material={materials['Material.090']} />
        <mesh geometry={nodes.Cube042_2.geometry} material={materials['Material.091']} />
      </group>
      <mesh geometry={nodes.POWER_隔离变_IT.geometry} material={materials['材质.004']} position={[3.481, 0.448, 2.46]} scale={[-2.861, 1.021, 1.021]} />
      <group position={[8.801, 1.067, 10.977]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.716, 2.006, 0.716]}>
        <mesh geometry={nodes.网格023.geometry} material={materials['lambert12.005']} />
        <mesh geometry={nodes.网格023_1.geometry} material={materials['lambert15.005']} />
        <mesh geometry={nodes.网格023_2.geometry} material={materials['lambert17.005']} />
      </group>
      <mesh geometry={nodes['10kV-SWG_SWG@201'].geometry} material={materials['lambert6.001']} position={[8.801, 1.067, 12.297]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.716, 2.006, 0.716]} />
      <mesh geometry={nodes['10kV-SWG_SWG@59-58'].geometry} material={materials['lambert12.011']} position={[8.801, 1.067, 10.977]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.716, 2.006, 0.716]} />
      <mesh geometry={nodes['10kV-SWG_RMU@环网柜X_RMU'].geometry} material={materials['材质.009']} position={[2.997, 1.337, 0.867]} rotation={[0, Math.PI / 2, 0]} scale={1.021} />
      <mesh geometry={nodes['220kV-TR_主变_sensor-ae'].geometry} material={materials['lambert19.002']} position={[0.181, 1.574, -11.437]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.047, 0.102, 0.102]} />
      <mesh geometry={nodes['220kV-TR_主变_scamera'].geometry} material={materials['blinn4.002']} position={[7.598, 3.206, -4.456]} rotation={[Math.PI / 2, 0, 0]} scale={0.302} />
      <mesh geometry={nodes['220kV-TR_主变_Obj3d66-9734994-16-771'].geometry} material={materials['Ground_Mat.001']} position={[3.194, 2.06, -13.639]} rotation={[0, 0.777, 0]} scale={0.001} />
      <mesh geometry={nodes['220kV-TR_主变_Cylinder033'].geometry} material={materials.PaletteMaterial002} position={[2.191, 5.607, -12.493]} rotation={[Math.PI, 0, Math.PI / 2]} scale={0.803} />
      <mesh geometry={nodes['110kV-CBL_电缆_Cable_Earthing_Box'].geometry} material={materials.protect1_Material} position={[8.114, 1.028, -2.952]} scale={[0.586, 0.336, 0.153]} />
      <mesh geometry={nodes['110kV-CBL_电缆_Cable_Circle'].geometry} material={nodes['110kV-CBL_电缆_Cable_Circle'].material} position={[-2.469, 0.535, -3.025]} rotation={[0, 0, -Math.PI / 2]} scale={0.163} />
    </group>
  )
}

useGLTF.preload('/Fullscene_0807_ver-transformed.glb')
