/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 FullScene_0721_TextGeo2.gltf --transform 
Files: FullScene_0721_TextGeo2.gltf [508.49KB] > D:\PDS_WorkSpace\pds_component_3d\public\Upload\Model\FullScene_0721_TextGeo2\FullScene_0721_TextGeo2-transformed.glb [1.76MB] (-247%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/public/FullScene_0721_TextGeo2-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.pillars.geometry} material={materials.PaletteMaterial001} position={[11.729, 1.145, 28.265]} scale={0.001} />
      <mesh geometry={nodes.switchGear001.geometry} material={materials['材质.009']} position={[2.997, 1.337, 0.867]} rotation={[0, 1.571, 0]} scale={1.021} />
      <group position={[5.486, 1.846, 25.725]} scale={0.001}>
        <mesh geometry={nodes.Mesh262.geometry} material={materials['07 - Default.001']} />
        <mesh geometry={nodes.Mesh262_1.geometry} material={materials.PaletteMaterial002} />
      </group>
      <mesh geometry={nodes.Rectangle2123442718.geometry} material={materials.PaletteMaterial003} position={[-2.955, 0.979, 29.959]} rotation={[0, -Math.PI / 2, 0]} scale={0.001} />
      <mesh geometry={nodes.Cube002.geometry} material={nodes.Cube002.material} position={[-13.708, 1.103, -0.444]} rotation={[0, 0, -Math.PI]} scale={[-0.03, -1.021, -0.473]} />
      <mesh geometry={nodes.Ground.geometry} material={materials['Ground_Mat.001']} position={[-0.842, -0.042, 2.91]} scale={[17.839, 17.839, 28.772]} />
      <mesh geometry={nodes.Cylinder004.geometry} material={materials.PaletteMaterial001} position={[-1.362, 5.607, -10.942]} rotation={[Math.PI, 0, Math.PI / 2]} scale={0.803} />
      <mesh geometry={nodes['Obj3d66-9734994-16-771003'].geometry} material={materials['Ground_Mat.001']} position={[2.527, 2.06, -12.089]} rotation={[0, 0.777, 0]} scale={0.001} />
      <mesh geometry={nodes.stairs003.geometry} material={materials.PaletteMaterial004} position={[5.383, 1.088, 10.262]} scale={0.001} />
      <mesh geometry={nodes.GIS_112_LCP_LOD2.geometry} material={materials['材质.011']} position={[-6.133, 0.192, 5.263]} scale={1.021} />
      <mesh geometry={nodes['sensor-ae'].geometry} material={materials['lambert19.002']} position={[0.121, 1.783, -9.854]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.032, 0.069, 0.069]} />
      <mesh geometry={nodes.Cube010.geometry} material={materials.protect1_Material} position={[6.831, 1.028, -2.952]} scale={[0.586, 0.336, 0.153]} />
      <group position={[8.801, 1.067, 7.429]} rotation={[1.571, 0, Math.PI / 2]} scale={[0.716, 2.006, 0.716]}>
        <mesh geometry={nodes.网格002.geometry} material={materials['lambert12.001']} />
        <mesh geometry={nodes.网格002_1.geometry} material={materials['lambert15.008']} />
        <mesh geometry={nodes.网格002_2.geometry} material={materials['lambert17.008']} />
        <mesh geometry={nodes.网格002_3.geometry} material={materials.G01_01} />
        <mesh geometry={nodes.网格002_4.geometry} material={materials['G01_01.001']} />
        <mesh geometry={nodes.网格002_5.geometry} material={materials['G01_01.002']} />
        <mesh geometry={nodes.网格002_6.geometry} material={materials['G01_01.003']} />
        <mesh geometry={nodes.网格002_7.geometry} material={materials['G01_01.004']} />
        <mesh geometry={nodes.网格002_8.geometry} material={materials['G01_01.005']} />
      </group>
      <group position={[8.801, 1.067, 10.139]} rotation={[1.571, 0, Math.PI / 2]} scale={[0.716, 2.006, 0.716]}>
        <mesh geometry={nodes.网格010.geometry} material={materials.G02_01} />
        <mesh geometry={nodes.网格010_1.geometry} material={materials['G02_01.001']} />
        <mesh geometry={nodes.网格010_2.geometry} material={materials['G02_01.002']} />
        <mesh geometry={nodes.网格010_3.geometry} material={materials['G02_01.003']} />
        <mesh geometry={nodes.网格010_4.geometry} material={materials['G02_01.004']} />
      </group>
      <mesh geometry={nodes.物体006.geometry} material={materials['blinn4.002']} position={[7.914, 4.376, -3.131]} rotation={[Math.PI / 2, 0, 0]} scale={0.402} />
      <mesh geometry={nodes['sensor-temp'].geometry} material={materials['lambert3.002']} position={[4.687, 2.535, 1.758]} rotation={[Math.PI / 2, 0, 0]} scale={0.738} />
      <mesh geometry={nodes.物体025.geometry} material={materials['lambert24.001']} position={[-1.877, 1.99, -3.585]} rotation={[Math.PI / 2, 0, 0]} scale={1.155} />
      <mesh geometry={nodes.物体027.geometry} material={materials['lambert25.001']} position={[-1.838, 1.907, -3.628]} rotation={[Math.PI / 2, 0, 0]} scale={1.155} />
      <mesh geometry={nodes['sensor-hfct'].geometry} material={materials['lambert26.001']} position={[-1.858, 1.936, -3.586]} rotation={[Math.PI / 2, 0, 0]} scale={1.155} />
      <mesh geometry={nodes['sensor-uhf'].geometry} material={materials['PDS_US02C_180124_3_2_blinn1.001']} position={[-4.446, 1.176, 9.693]} rotation={[Math.PI / 2, 0, 0.917]} scale={1.882} />
    </group>
  )
}

useGLTF.preload('/public/FullScene_0721_TextGeo2-transformed.glb')
